services:

  worker:
    image: k2m30/ruby_worker:1.0
    build:
      context: worker/
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env
    networks:
      - default

  server:
    image: k2m30/js_server:1.0
    build:
      context: server/
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env
    ports:
      - 8081:8080
    networks:
      - default

  client:
    image: k2m30/nginx_client:1.0
    build:
      context: client/
      dockerfile: Dockerfile
    depends_on:
      - server
      - db
    ports:
      - 8080:80
    networks:
      - default

  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - default


  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8082:8082
    networks:
      - default
    depends_on:
      - db

networks:
  default:
    driver: bridge
    attachable: true
