version: "3"
services:

  worker:
#    image: k2m30/ruby_worker:1.3
    build:
      context: ./worker
    depends_on:
      - db
    env_file: .env
    volumes:
      - ${PWD}/sheets.json:/sheets.json
    networks:
      - default

  server:
    image: k2m30/js_server:1.0
    depends_on:
      - db
    env_file: .env
    expose:
      - 8080
    networks:
      - default

  client:
    image: k2m30/nginx_client:1.0
    depends_on:
      - server
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-challenges:/etc/letsencrypt/challenges
    networks:
      default:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file: .env
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - default

volumes:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      device: ./letsencrypt
      o: bind

  certbot-challenges:
    driver: local
    driver_opts:
      type: none
      device: ./letsencrypt/challenges
      o: bind

networks:
  default:
    driver: bridge
