name: Build and push Docker images

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}          
    steps:

      - name: Check-out
        uses: actions/checkout@v2
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MYSQL_ROOT_USERNAME: root
          envkey_MYSQL_ROOT_PASSWORD: secret
          envkey_MYSQL_HOST: db
          envkey_MYSQL_DATABASE: db
          envkey_GOOGLE_ACCOUNT_TYPE: service_account
          envkey_GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          envkey_GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          envkey_SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          envkey_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          envkey_REDIS_HOST: redis
          envkey_REDIS_PASSWORD: secret

      - name: Docker compose build
        run: docker-compose build
        
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      - name: Docker push
        run: docker-compose push
        
