name: Deploy to Digital Ocean

on: 
  push:
    branches: 
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: SSH key
        env: 
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: echo $SSH_KEY > ~/.ssh/id_rsa
      - name: Add droplet to the list of known hosts
        run: |
          ssh-keyscan -H $(doctl compute droplet list -o json |jq -r '.[]| "\(.networks.v4[1].ip_address)"') >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          doctl compute ssh docker-spiski --ssh-command 'cd spiski && docker-compose stop worker && docker-compose pull && docker-compose up -d client worker'
